version: "3"

services:
  database:
    image: "postgres:latest"
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/pg_data
    networks:
      - postgres-network
    volumes:
      - /home/postgres/db-data/:/var/lib/pg_data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5433:443"
    env_file:
      - .env
    environment:
      SESSION_DB_PATH: /var/lib/pg_admin
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - /home/postgres/pgadmin-data/:/var/lib/pg_admin
      - /tmp/certs/pgadmin_server.crt:/certs/server.cert
      - /tmp/certs/pgadmin_server.key:/certs/server.key

networks:
  postgres-network:
    driver: bridge